#!/usr/bin/env php

<?php

require __DIR__ . '/packager.php';

$executable = array_shift($argv);
$manifest = array_shift($argv);
$file_name = array_shift($argv);

$pkg = new Packager($manifest);

echo "Packager is building $file_name with $manifest\n\n";
echo "Included Components:\n";

$scripts = (empty($argv)) ? $pkg->get_all_scripts() : $pkg->components_to_scripts($argv);

foreach ($scripts as $script){
	echo "  -$script: [" . implode(", ", $pkg->get_script_provides($script)) . "]\n";
}

echo "\n";

$pkg->write_components($file_name, $argv);

?>
