#!/usr/bin/env php
<?php

$stderr = fopen('php://stderr', 'w');

require dirname(__FILE__) . '/packager.php';

$executable = array_shift($argv);

if (!count($argv) || $argv[0] == '-h' || $argv[0] == '--help'){
	fwrite($stderr, "Usage: build <package_manifest> [components...]\n");
	exit(1);
}

$package = array_shift($argv);

$pkg = new Packager($package);
$package_name = $pkg->get_package_name();

fwrite($stderr, "Packager is building $package_name\n\n");
fwrite($stderr, "Included Components:\n");

$files = (empty($argv)) ? $pkg->get_all_files() : $pkg->components_to_files($argv);

foreach ($files as $file){
	$name = $pkg->get_file_name($file);
	fwrite($stderr, "- $name: [" . implode(', ', $pkg->get_file_provides($file)) . "]\n");
}

echo (empty($argv)) ? $pkg->build_from_files($files) : $pkg->build_from_components($argv);

fclose($stderr);

?>
